language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Z4jaeIs1pnMuJ0dt+2q7G0ihlbSz03AVguYpMk2hTKIJQUbKFHFSiTRIGzsT4M6/NzNZaFGhQegu94+gXP/lE5h0WacyQJNLPKpiDGJKZQN8V4n07BjiU8OHLLYFkJcLrdT9lZ3+O89fR2QCPLnkZf1FeuksMnRIsTVMoJ+izTC0QPClgCkMnX0uJTwY+CEBpW6t2ciFJZoelsE5KwashtOIclLBuJPdu/+2Jb7AC2dUhXhLMo1JlRqLe+kHUVg+zd6RwOoGUmated1JGuSsH9dY96hd8F/68n/Y6nz92QDvhk68KLbsmwBaaF4NDPxU4W1E85L+2sA26cWzgbSD39XMoLai8G4vur+VATtZr4OOqOgqYU7fxUJhRwightoBvubo0DvlII5Guj/bzxypwB98Zwt1VGlwujwf2EHI9WJ4uKJgkvZ+DN3MXR1F+/YLxn+ZcxPoRaVcZrg+MoirsWtUkC9ye/y/+5eoX5WsJtlhvrasEeKQ3M+4L1GyyNAR2kagbzuvjTq5FgN+LjPo7gE3O9JqhiSNEqP+eeB5YAgcGtxpiyJu51z1jW5r+CWopJipT0x7fdkKHGmdMpl7IIyzaBsoAe+7FzYHJyq3xwOOKJzlyDXin7CpuqoEnxMfwPIPdvIJRZCMOTWZekaf0wfRFxmrciTTj5GdVCLRVD0=
  app: github-travis-heroku
  skip_cleanup: 'true'
