language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: {b7a47c34d96b02452a9db77d97d098c717d4160f}
  app: fast-refuge-79505
  on:
    repo: akwanmtl/github-travis-heroku