language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Kyo7PWAW7sl3O0FOn5VLe9je9kg0pQzV38U4VKma3N4vU+IjYRmDl3Pzoy7xRGGp3AFsrNnqR4zrdQoHmzbxkgp9pA3W62j3nLRWQGWmwwnJdHgiyhDMGqn8PPqpXhLv0hzgAQvcGPvMVB7DX84vnIE4PNOrFVTipFY2Fta1PPMBNbUIn9Jk6m8Ys1K6UA9MUR04jODnAtB7uo46JlvLpxYxtoCkHNX9Lje59RsMCuRKhGZeHq8tAkuh76WPZYH0LK7x65NBcmsNNNn5yRhfwpB/Nu84Tadt6kW+Oqqyz6FhiygjioksIcMdOi59pgyo9fAj5vw4QT1xNlXWJ5cQo/oTtyBNWOM9npwsjfCiA3IBQDSdda1Qzt1jkCBbO6cXmBg6Gy0vsi9UQX2ubDPT2R0AQLIA/ypQKsyK8UPOhNxo10RrYEw9kYatFEZVkK1KH+qnE/bW4yYT5uIEg7VbgsVJGQndmWuhQNxAKq90glfi+Gzz0e0Uspt+0l7Uu2byrnMGNExhsznurAn/onF9371Gg0EKCwvlGAxBo/dxZGO1vCoLretMGuXQYaeEyc9386wEu++kBjVU9UEkrMS60+IOuxZQexlemXX7oPVtOrFgFbr64vwBbox9HhZTQo4R22dBJLUUNvkSg6hISa9TDJjT97Cx5He3Dv09OW82nQk=
  app: unittest-travis-heroku
  skip_cleanup: 'true'
